site_name: PesterExplorer
site_url: http://heyitsgilbert.github.io/PesterExplorer
repo_url: http://github.com/HeyItsGilbert/PesterExplorer
theme:
  name: readthedocs
nav:
  - Home: "index.md"
  - Changelog: "https://github.com/HeyItsGilbert/PesterExplorer/blob/main/CHANGELOG.md"
  - en-US:
      - en-US/
plugins:
  - search
  - include_dir_to_nav
